### ISSUE TITLE
Reset password on login 

### ISSUE THREAD

**Issue by xjarlie** [Xjarlie/tv-recommend#41]
No way to reset password on login screen if user forgot their password

**Comment by mehabhalodiya** [comment]
You want to add link of forgot password in login.html?

**Comment by xjarlie** [comment]
> You want to add link of forgot password in login.html?

Basically the user should be able to reset their password without logging in, as I've had to manually reset people's passwords if they forget and aren't signed in

**Comment by mehabhalodiya** [comment]
Okay, I will get back to you soon about the same!

**Comment by xjarlie** [comment]
> Okay, I will get back to you soon about the same!

OK, sounds good!

**Comment by xjarlie** [comment]
Added reset password button on  `login.html`
