### ISSUE TITLE
Add category tag to watchlist and profile

### ISSUE THREAD

**Issue by xjarlie** [Xjarlie/tv-recommend#50]
Should display `TV/Movie` tag on watchlist and profile pages to avoid confusion about items with same name

**Comment by prathamesh-borse** [comment]
I would like to work on this issue?

**Comment by xjarlie** [comment]
> I would like to work on this issue?

Sure, it's fairly simple to do, you can essentially copy the code from the homepage and put it in the post display in watchlist and profile pages. If you need anything explaining feel free to comment

**Comment by prathamesh-borse** [comment]
What is the name of home page and which code I have to copy from that?

**Comment by xjarlie** [comment]
The home page is index.html, and you need to get the html of the category tags (where it says 'film' here) as well as the javascript that gets the post data and puts it in the category tag
![image](https://user-images.githubusercontent.com/49068203/103149105-d267df80-47a9-11eb-822e-339c3904a649.png)

**Comment by xjarlie** [comment]
Added
